### ISSUE TITLE
 Send information by a hash or something

### ISSUE THREAD

**Issue by lramosduarte** [jahraphael/raiderio-addon#15]
Today getting information about myths is done only with the TOP100, correct?

Can not make the addon get the information of all the myths in the game? Generating an information string for a manual user upload

**Comment by Chikuss2** [comment]
That could help, because I did a lot of mythic and don't get score cause they are consider low to top100 and because of that, ppl dont invite me to mythic because I have low score =(

**Comment by jahraphael** [comment]
Now that Blizzard has expanded the API to include top 500 this issue is much less problematic. The complication with user-submitted data is that it can be tampered with.

We're going to close this out for now as we adjust to this Top 500 world.
