### ISSUE TITLE
# of M+ runs is inacurate

### ISSUE THREAD

**Issue by Cybercruiser** [jahraphael/raiderio-addon#19]
Not sure where this number is pulled from but over the course of 3 weeks my timed runs have gone from more than 15 to 12 and then 13. for example my character had 12 m+15's completed this monday, and tuesday morning only showed an increase of 1, despite doing at least 5 dungeons varying from 15 to 19. And next tuesday I can count on this number either declining or increasing to a seemingly random number yet again. whether it is an issue with the addon, or the website itself as I cannot find where it stores this number on the website.

**Comment by jahraphael** [comment]
No response in several weeks. Closing this out. Please re-open if you have the additional info to follow up with.
