### ISSUE TITLE
kr-Realms -- suggest modification

### ISSUE THREAD

**Issue by masyal** [jahraphael/raiderio-addon#24]
- suggest modification -

https://github.com/jahraphael/raiderio-addon/blob/dcf8710845475a219196b0d74bd5d56aa599e031/db/db_realms.lua#L1007

https://github.com/jahraphael/raiderio-addon/blob/dcf8710845475a219196b0d74bd5d56aa599e031/db/db_kr_alliance_characters.lua#L20

https://github.com/jahraphael/raiderio-addon/blob/dcf8710845475a219196b0d74bd5d56aa599e031/db/db_kr_horde_characters.lua#L20

Wrong Realm : ["윈드런너"] 
Modify Request Realm : ["윈드러너"]

[윈드런너] (x) --->> ["윈드러너"] (o)

**Comment by jahraphael** [comment]
Thanks. I commented in the PR, but figured I would follow up here as well. We've made the changes that should correct this realm in the next addon update, but do you know if there are any other Korean realm names that are incorrect?

**Comment by masyal** [comment]
https://github.com/jahraphael/raiderio-addon/blob/4918231d575db8d068d6cc6f0821fff6e3d2b080/db/db_realms.lua#L995

https://github.com/jahraphael/raiderio-addon/blob/4918231d575db8d068d6cc6f0821fff6e3d2b080/db/db_kr_alliance_characters.lua#L16

https://github.com/jahraphael/raiderio-addon/blob/4918231d575db8d068d6cc6f0821fff6e3d2b080/db/db_kr_horde_characters.lua#L16

Wrong Realm : ["노르가논"]
Modify Request Realm : ["노르간논"]

[노르가논] (x) --->> ["노르간논"] (o)

**Comment by jahraphael** [comment]
Thanks! This is fixed in the DB now, so should be reflected in the next addon update.

**Comment by jahraphael** [comment]
Closing this out. If there are any other realms that exhibit problems, please open a new ticket. Thanks! :)
