### ISSUE TITLE
Raider io wont update. 

### ISSUE THREAD

**Issue by Snieaky** [jahraphael/raiderio-addon#26]
I always have a delay on updating raider io. In wow it will say addon is 3 days old. 
When i do reinstall the addon it self it doesnt rly help. 
any advice?

**Comment by jahraphael** [comment]
Hi there - there's been some slowdowns on CurseForge recently where tagged commits aren't resulting in updated builds right away like they used to be. We did just see a new build come through earlier tonight though, so I would go to the project page and download it there: https://wow.curseforge.com/projects/raiderio
