### ISSUE TITLE
Latest DB push was only tw and kr

### ISSUE THREAD

**Issue by tombomb** [jahraphael/raiderio-addon#30]
last update pushed has a timestamp of date="2018-05-16T08:01:09Z" checked here saw that only tw and kr were pushed. Helped calm an angry guy in #addon-discussions.

Thanks for the amazing product, keep up the amazing work

**Comment by jahraphael** [comment]
Thanks Tombomb. I'd missed this message here - but I'd seen you bring this up in Discord.

This issue was fixed shortly after.
