### ISSUE TITLE
character's data update

### ISSUE THREAD

**Issue by VITALIIKIMEPAM** [jahraphael/raiderio-addon#42]
Hi all, i really like this wow addon, but quite often i'm facing with annoying issue.
As far as I understand character's database located locally in addon directory, so when i want to check any player, remote calls do not occurs and all data is obtained locally. So i have to update local addon database whenever this one is updated.

Is there any workaround like (isDataOutdated -> perform remote call via REST -> update character's data)
If updating all the data requires high network costs, perform a point update, i.e, the specific player you check

Does anybody mind if I'll take this issue for investigation and probably for patching?

**Comment by WFrancois** [comment]
Hey !

Yes, the addon works like that, so you need to update it regularly.

What you suggest is a good idea, but sadly, you can't make any external call from an addon, this is why we need to have all the data locally :/

If you want to make it easier, and if you use Twitch to manage your addon, there's a settings in the client to download update automatically (though it's sometimes buggy :/); it's under Settings > Addon Settings > Auto Install updates.
