### ISSUE TITLE
option to overwrite default language

### ISSUE THREAD

**Issue by Sunz3r** [jahraphael/raiderio-addon#44]
Usualy we use only english shortcuts for dungeons. German shortcuts are very weird.

**Comment by Badango** [comment]
Just noticed that stupid new shortcuts too, i first assumed there might be something buggy that mixes letters around...^^

As a workaround i just deleted the german locale file. Although that worked, i don't wanna have to do that after each update, so please add such an option or switch those shortcuts back to the english ones, no one here uses german shortcuts for dungeons or raids anyways.

**Comment by WFrancois** [comment]
Hey !

Just know that we're looking into ways to avoid you having to modify the file :)

**Comment by WFrancois** [comment]
Hey !

We decided to remove the acronym's translation, so if you update to the latest release (v201806211634) there shouldn't be any german acronyms ! :)
