### ISSUE TITLE
My M+ Profile Not Highlighting Dungeon

### ISSUE THREAD

**Issue by jahraphael** [jahraphael/raiderio-addon#49]
Saw this reported on Curse:

```Since the last reset, Best runs by Dungeon doesn't always highlight the dungeon with green color, what happened?```

**Comment by WFrancois** [comment]
Ok, I think I was able to reproduce this.

This happens when the group you're hovering doesn't have a score.
Looking into a fix.

**Comment by InfernalDark** [comment]
Thanks for the fix!
