### ISSUE TITLE
Change Server

### ISSUE THREAD

**Issue by BlueNightSky** [jahraphael/raiderio-addon#9]
Hi! 
I changed the server since last week, addons now can not find my own score, can help to fix it?
Before: WorldTree-三皈依 (Taiwan - Alliance)
After:    暗影之月-三皈依 (Taiwan - Alliance)
Player name has not changed, Thank You!

**Comment by jahraphael** [comment]
Hi there - please open this as a ticket on the official Raider.IO support system (click the little question mark on any page on the site, or email support@raider.io). We want to keep issues on the github here specific to problems/requests related to the addon itself.
